#!/bin/bash
# Author:  own3mall <own3mall@gmail.com>
# About:  Script that pulls the transifex files, puts them in the OGP stucture, copies the structure to the website and every module folder, runs a git pull, git clean, git commit, git push to remote repositories :D

######################
#  FUNCTIONS #########
######################
function setGlobalVars(){
	# Variables
	transifexDir="/home/own3mall/transifex"
	gitDir="/home/own3mall/github"
	logFile="/home/own3mall/transifex/logFile"
	gitPath="/usr/bin/git"
	transifexUser="{YOUR_TRANSIFEX_USER_HERE}"
	transifexPass="{YOUR_TRANSIFEX_PASS_HERE}"
}

function clearLogFile(){
	# New log file
	> "$logFile"
}

function copyFile(){
	mkdir -p "../${langPath}/modules"
	if [ "$OGPFileNamePRE" != "global" ] && [ "$OGPFileNamePRE" != "install" ]; then
		cp "$f" "../${langPath}/modules/${OGPFileNamePHP}"
	else
		cp "$f" "../${langPath}/${OGPFileNamePHP}"
	fi
}

function getTranslations(){
	cd "$transifexDir"
	rm -rf ".tx"
	rm -rf translations
	/usr/local/bin/tx init --host="https://www.transifex.com" --user="${transifexUser}" --pass="${transifexPass}"
	/usr/local/bin/tx set --auto-remote https://www.transifex.com/opengamepanel/ogp
	/usr/local/bin/tx pull -a -s
	if [ ! -d "translations" ]; then
		logMessage "Failed to retrieve translation files."
		exit
	fi
	rm -rf staging
	mkdir -p staging
	cp -r translations/* staging
}

function makeOGPStructure(){
	cd "$transifexDir"
	cd staging
	for folder in `find ./* -type d`; do
		
		OGPFileNamePRE=$(cut -d "." -f 3 <<< "$folder" | grep -o ".*[^php]")
		OGPFileNamePHP="${OGPFileNamePRE}.php"
		
		# Logging 
		logMessage "Current translation folder is $folder"
		logMessage "OGP module name is $OGPFileNamePRE"
		logMessage "OGP full language file name is $OGPFileNamePHP"
		
		if [ -e "$folder" ]; then
			cd "$folder"
			for f in `find ./* -type f | sed "s|^\./||"`; do
				case "$f" in
				"en.php")
					langPath="lang/English"
					copyFile
					;;
				"da.php")
					langPath="lang/Danish"
					copyFile
					;;
				"de.php")
					langPath="lang/German"
					copyFile
					;;
				"es.php")
					langPath="lang/Spanish"
					copyFile
					;;
				"fr.php")
					langPath="lang/French"
					copyFile
					;;
				"hu.php")
					langPath="lang/Hungarian"
					copyFile
					;;
				"pl.php")
					langPath="lang/Polish"
					copyFile
					;;
				"pt.php")
					langPath="lang/Portuguese"
					copyFile
					;;
				"ru.php")
					langPath="lang/Russian"
					copyFile
					;;
				esac
			done
			cd ..
		fi
	done
}

function logMessage(){
	if [ ! -z "$1" ]; then
		echo -e "$1" >> "$logFile"
	fi
}

function copyOGPStructureToAllGitRepos(){
	cd "$transifexDir/staging"
	if [ -d "lang" ] && [ -e "lang" ]; then
		# Loop through git folders
		for folder in `find "${gitDir}" -mindepth 1 -maxdepth 1 -type d`; do
			logMessage "Current github folder is $folder"
			cd "$folder"
			"$gitPath" pull
			cp -rf "$transifexDir/staging/lang" "$folder"
			"$gitPath" clean -f
			"$gitPath" commit -am "Transifex Language Updates - Generated by own3mall's auto script."
			"$gitPath" push
		done
	fi
}

######################
#  Main ##############
######################
setGlobalVars
clearLogFile
getTranslations
makeOGPStructure
copyOGPStructureToAllGitRepos

